project_id = "figeuiotixafbnbwgvpi"

[functions.api-docs]
verify_jwt = false

[functions.create-subscription-session]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false