// This file is auto-generated by Lovable. Do not modify it.

import { supabase } from "../supabase/client";

type SignInOptions = {
  redirect_uri?: string;
  extraParams?: Record<string, string>;
};

type OAuthProvider = "google" | "apple";

type LovableAuth = {
  signInWithOAuth: (
    provider: OAuthProvider,
    opts?: { redirect_uri?: string; extraParams?: Record<string, string> }
  ) => Promise<
    | { redirected: true }
    | { redirected?: false; tokens?: any; error?: Error | null }
    | any
  >;
};

let lovableAuthPromise: Promise<LovableAuth> | null = null;

async function getLovableAuth(): Promise<LovableAuth> {
  if (!lovableAuthPromise) {
    lovableAuthPromise = import("@lovable.dev/cloud-auth-js")
      .then(({ createLovableAuth }) => createLovableAuth({}) as LovableAuth)
      .catch((e) => {
        lovableAuthPromise = null;
        throw e;
      });
  }
  return lovableAuthPromise;
}

export const lovable = {
  auth: {
    signInWithOAuth: async (provider: OAuthProvider, opts?: SignInOptions) => {
      let auth: LovableAuth;
      try {
        auth = await getLovableAuth();
      } catch (e) {
        return { error: e instanceof Error ? e : new Error(String(e)) };
      }

      const result = await auth.signInWithOAuth(provider, {
        redirect_uri: opts?.redirect_uri,
        extraParams: {
          ...opts?.extraParams,
        },
      });

      if ((result as any)?.redirected) {
        return result;
      }

      if ((result as any)?.error) {
        return result;
      }

      try {
        await supabase.auth.setSession((result as any).tokens);
      } catch (e) {
        return { error: e instanceof Error ? e : new Error(String(e)) };
      }
      return result;
    },
  },
};
